default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
    - id: remove-crlf
- repo: https://github.com/jguttman94/pre-commit-gradle
  rev: v0.3.0
  hooks:
    - id: gradle-spotless
    - id: gradle-check
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.11.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      args: ["--config", ".config/commitlint.config.ts"]
      additional_dependencies: ['@commitlint/config-conventional', '@commitlint/types']
